// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension WeatherClientTypes {
    public enum Announcements: Swift.Equatable {
        case police(WeatherClientTypes.Message)
        case fire(WeatherClientTypes.Message)
        case health(WeatherClientTypes.Message)
        case sdkUnknown(Swift.String)
    }

}
