// Code generated by smithy-swift-codegen. DO NOT EDIT!

import class SmithyJSON.Reader
import enum SmithyReadWrite.ReaderError

extension WeatherClientTypes.Baz {

    static func read(from reader: SmithyJSON.Reader) throws -> WeatherClientTypes.Baz {
        guard reader.hasContent else { throw SmithyReadWrite.ReaderError.requiredValueNotPresent }
        var value = WeatherClientTypes.Baz()
        value.baz = try reader["baz"].readIfPresent()
        value.bar = try reader["bar"].readIfPresent()
        return value
    }
}
