// Code generated by smithy-swift-codegen. DO NOT EDIT!

import class SmithyJSON.Reader
import class SmithyJSON.Writer
import enum SmithyReadWrite.ReaderError

extension WeatherClientTypes.CityCoordinates {

    static func write(value: WeatherClientTypes.CityCoordinates?, to writer: SmithyJSON.Writer) throws {
        guard let value else { return }
        try writer["latitude"].write(value.latitude)
        try writer["longitude"].write(value.longitude)
    }

    static func read(from reader: SmithyJSON.Reader) throws -> WeatherClientTypes.CityCoordinates {
        guard reader.hasContent else { throw SmithyReadWrite.ReaderError.requiredValueNotPresent }
        var value = WeatherClientTypes.CityCoordinates()
        value.latitude = try reader["latitude"].readIfPresent()
        value.longitude = try reader["longitude"].readIfPresent()
        return value
    }
}
