// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyReadWrite

extension WeatherClientTypes {
    public struct CitySummary: Swift.Equatable {
        public var `case`: Swift.String?
        /// This member is required.
        public var cityId: Swift.String?
        /// This member is required.
        public var name: Swift.String?
        public var number: Swift.String?

        public init(
            `case`: Swift.String? = nil,
            cityId: Swift.String? = nil,
            name: Swift.String? = nil,
            number: Swift.String? = nil
        )
        {
            self.`case` = `case`
            self.cityId = cityId
            self.name = name
            self.number = number
        }
    }

}
