// Code generated by smithy-swift-codegen. DO NOT EDIT!

import class SmithyJSON.Reader
import class SmithyJSON.Writer
import enum SmithyReadWrite.ReaderError

extension WeatherClientTypes.CitySummary {

    static func write(value: WeatherClientTypes.CitySummary?, to writer: SmithyJSON.Writer) throws {
        guard let value else { return }
        try writer["case"].write(value.`case`)
        try writer["cityId"].write(value.cityId)
        try writer["name"].write(value.name)
        try writer["number"].write(value.number)
    }

    static func read(from reader: SmithyJSON.Reader) throws -> WeatherClientTypes.CitySummary {
        guard reader.hasContent else { throw SmithyReadWrite.ReaderError.requiredValueNotPresent }
        var value = WeatherClientTypes.CitySummary()
        value.cityId = try reader["cityId"].readIfPresent()
        value.name = try reader["name"].readIfPresent()
        value.number = try reader["number"].readIfPresent()
        value.`case` = try reader["case"].readIfPresent()
        return value
    }
}
