// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension CreateCityInput {

    static func urlPathProvider(_ value: CreateCityInput) -> Swift.String? {
        return "/city"
    }
}
