// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension CreateCityInput: Swift.Encodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case city
        case coordinates
        case name
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let city = self.city {
            try encodeContainer.encode(city, forKey: .city)
        }
        if let coordinates = self.coordinates {
            try encodeContainer.encode(coordinates, forKey: .coordinates)
        }
        if let name = self.name {
            try encodeContainer.encode(name, forKey: .name)
        }
    }
}
