// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct CreateCityOutputBody {
    let cityId: Swift.String?
}

extension CreateCityOutputBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case cityId
    }

    public init(from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let cityIdDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .cityId)
        cityId = cityIdDecoded
    }
}
