// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct CreateCityInputBody {
    let name: Swift.String?
    let coordinates: WeatherClientTypes.CityCoordinates?
    let city: WeatherClientTypes.CitySummary?
}

extension CreateCityInputBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case city
        case coordinates
        case name
    }

    public init(from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let nameDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .name)
        name = nameDecoded
        let coordinatesDecoded = try containerValues.decodeIfPresent(WeatherClientTypes.CityCoordinates.self, forKey: .coordinates)
        coordinates = coordinatesDecoded
        let cityDecoded = try containerValues.decodeIfPresent(WeatherClientTypes.CitySummary.self, forKey: .city)
        city = cityDecoded
    }
}
