// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension WeatherClientTypes.Foo: Swift.Codable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case bar
        case baz
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let bar = self.bar {
            try encodeContainer.encode(bar, forKey: .bar)
        }
        if let baz = self.baz {
            try encodeContainer.encode(baz, forKey: .baz)
        }
    }

    public init(from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let bazDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .baz)
        baz = bazDecoded
        let barDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .bar)
        bar = barDecoded
    }
}
