// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension WeatherClientTypes {
    public struct Foo {
        public var bar: Swift.String?
        public var baz: Swift.String?

        public init(
            bar: Swift.String? = nil,
            baz: Swift.String? = nil
        )
        {
            self.bar = bar
            self.baz = baz
        }
    }

}
