// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension GetCurrentTimeOutput: ClientRuntime.HttpResponseBinding {
    public init(httpResponse: ClientRuntime.HttpResponse, decoder: ClientRuntime.ResponseDecoder? = nil) async throws {
        if let data = try await httpResponse.body.readData(),
            let responseDecoder = decoder {
            let output: GetCurrentTimeOutputBody = try responseDecoder.decode(responseBody: data)
            self.time = output.time
        } else {
            self.time = nil
        }
    }
}
