// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyHTTPAPI
import SmithyJSON
import SmithyReadWrite

extension GetCityAnnouncementsOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HttpResponse) async throws -> GetCityAnnouncementsOutput {
        var value = GetCityAnnouncementsOutput()
        if let lastUpdatedHeaderValue = httpResponse.headers.value(for: "x-last-updated") {
            value.lastUpdated = TimestampFormatter(format: .httpDate).date(from: lastUpdatedHeaderValue)
        }
        return value
    }
}
