// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct GetCityAnnouncementsInputBody: Swift.Equatable {
}

extension GetCityAnnouncementsInputBody: Swift.Decodable {

    public init(from decoder: Swift.Decoder) throws {
    }
}
