// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension GetCityOutput: ClientRuntime.HttpResponseBinding {
    public init(httpResponse: ClientRuntime.HttpResponse, decoder: ClientRuntime.ResponseDecoder? = nil) async throws {
        if let data = try await httpResponse.body.readData(),
            let responseDecoder = decoder {
            let output: GetCityOutputBody = try responseDecoder.decode(responseBody: data)
            self.city = output.city
            self.coordinates = output.coordinates
            self.name = output.name
        } else {
            self.city = nil
            self.coordinates = nil
            self.name = nil
        }
    }
}
