// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct GetCityImageOutputBody: Swift.Equatable {
    let image: ClientRuntime.ByteStream?
}

extension GetCityImageOutputBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case image
    }

    public init(from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let imageDecoded = try containerValues.decodeIfPresent(ClientRuntime.ByteStream.self, forKey: .image)
        image = imageDecoded
    }
}
