// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct GetCityImageOutput {
    /// This member is required.
    public var image: ClientRuntime.ByteStream?

    public init(
        image: ClientRuntime.ByteStream? = nil
    )
    {
        self.image = image
    }
}
