// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyTestUtil

enum GetCityImageOutputError: ClientRuntime.HttpResponseErrorBinding {
    static func makeError(httpResponse: ClientRuntime.HttpResponse, decoder: ClientRuntime.ResponseDecoder? = nil) async throws -> Swift.Error {
        let defaultError = try await SmithyTestUtil.JSONError(httpResponse: httpResponse)
        switch defaultError.errorType {
            case "NoSuchResource": return try await NoSuchResource(httpResponse: httpResponse, decoder: decoder, message: defaultError.errorMessage)
            default: return try await ClientRuntime.UnknownHTTPServiceError.makeError(httpResponse: httpResponse, message: defaultError.errorMessage, typeName: defaultError.errorType)
        }
    }
}
