// Code generated by smithy-swift-codegen. DO NOT EDIT!

import enum Smithy.ByteStream

public struct GetCityImageOutput {
    /// This member is required.
    public var image: Smithy.ByteStream?

    public init(
        image: Smithy.ByteStream? = nil
    )
    {
        self.image = image
    }
}
