// Code generated by smithy-swift-codegen. DO NOT EDIT!

import Foundation

public struct GetCurrentTimeOutput {
    /// This member is required.
    public var time: Foundation.Date?

    public init(
        time: Foundation.Date? = nil
    )
    {
        self.time = time
    }
}
