// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension GetCityInput {

    static func urlPathProvider(_ value: GetCityInput) -> Swift.String? {
        guard let cityId = value.cityId else {
            return nil
        }
        return "/cities/\(cityId.urlPercentEncoding())"
    }
}
