// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct GetCityOutput {
    public var city: WeatherClientTypes.CitySummary?
    /// This member is required.
    public var coordinates: WeatherClientTypes.CityCoordinates?
    /// This member is required.
    public var name: Swift.String?

    public init(
        city: WeatherClientTypes.CitySummary? = nil,
        coordinates: WeatherClientTypes.CityCoordinates? = nil,
        name: Swift.String? = nil
    )
    {
        self.city = city
        self.coordinates = coordinates
        self.name = name
    }
}
