// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

/// The input used to get a city.
public struct GetCityInput: Swift.Equatable {
    /// This member is required.
    public var cityId: Swift.String?

    public init(
        cityId: Swift.String? = nil
    )
    {
        self.cityId = cityId
    }
}
