// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyReadWrite

public struct GetCurrentTimeOutput: Swift.Equatable {
    /// This member is required.
    public var time: ClientRuntime.Date?

    public init(
        time: ClientRuntime.Date? = nil
    )
    {
        self.time = time
    }
}
