// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct GetCurrentTimeInputBody: Swift.Equatable {
}

extension GetCurrentTimeInputBody: Swift.Decodable {

    public init(from decoder: Swift.Decoder) throws {
    }
}
