// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct GetCityInputBody: Swift.Equatable {
}

extension GetCityInputBody: Swift.Decodable {

    public init(from decoder: Swift.Decoder) throws {
    }
}
