// Code generated by smithy-swift-codegen. DO NOT EDIT!

import class SmithyHTTPAPI.HttpResponse
import enum Smithy.ByteStream

extension GetCityImageOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HttpResponse) async throws -> GetCityImageOutput {
        var value = GetCityImageOutput()
        switch httpResponse.body {
        case .data(let data):
            value.image = .data(data)
        case .stream(let stream):
            value.image = .stream(stream)
        case .noStream:
            value.image = nil
        }
        return value
    }
}
