// Code generated by smithy-swift-codegen. DO NOT EDIT!

import Foundation

public struct GetCityAnnouncementsOutput {
    public var lastUpdated: Foundation.Date?

    public init(
        lastUpdated: Foundation.Date? = nil
    )
    {
        self.lastUpdated = lastUpdated
    }
}
