// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct GetCurrentTimeOutputBody: Swift.Equatable {
    let time: ClientRuntime.Date?
}

extension GetCurrentTimeOutputBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case time
    }

    public init(from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let timeDecoded = try containerValues.decodeTimestampIfPresent(.dateTime, forKey: .time)
        time = timeDecoded
    }
}
