// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyReadWrite

public struct GetCityImageOutput: Swift.Equatable {
    /// This member is required.
    public var image: ClientRuntime.ByteStream?

    public init(
        image: ClientRuntime.ByteStream? = nil
    )
    {
        self.image = image
    }
}
