// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension GetCurrentTimeInput {

    static func urlPathProvider(_ value: GetCurrentTimeInput) -> Swift.String? {
        return "/current-time"
    }
}
