// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyReadWrite

public struct GetCityAnnouncementsOutput {
    public var lastUpdated: ClientRuntime.Date?

    public init(
        lastUpdated: ClientRuntime.Date? = nil
    )
    {
        self.lastUpdated = lastUpdated
    }
}
