// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension GetCurrentTimeInput {

    static func urlPathProvider(_ value: GetCurrentTimeInput) -> Swift.String? {
        return "/current-time"
    }
}
