// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct GetCurrentTimeInputBody {
}

extension GetCurrentTimeInputBody: Swift.Decodable {

    public init(from decoder: Swift.Decoder) throws {
    }
}
