// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension GetCityImageOutput: ClientRuntime.HttpResponseBinding {
    public init(httpResponse: ClientRuntime.HttpResponse, decoder: ClientRuntime.ResponseDecoder? = nil) async throws {
        switch httpResponse.body {
        case .data(let data):
            self.image = .data(data)
        case .stream(let stream):
            self.image = .stream(stream)
        case .noStream:
            self.image = nil
        }
    }
}
