// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct GetCityImageInputBody {
}

extension GetCityImageInputBody: Swift.Decodable {

    public init(from decoder: Swift.Decoder) throws {
    }
}
