// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension GetForecastInput {

    static func urlPathProvider(_ value: GetForecastInput) -> Swift.String? {
        guard let cityId = value.cityId else {
            return nil
        }
        return "/cities/\(cityId.urlPercentEncoding())/forecast"
    }
}
