// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyJSON
import SmithyReadWrite

extension GetForecastOutput {

    static var httpBinding: SmithyReadWrite.WireResponseOutputBinding<ClientRuntime.HttpResponse, GetForecastOutput, SmithyJSON.Reader> {
        { httpResponse, responseDocumentClosure in
            let responseReader = try await responseDocumentClosure(httpResponse)
            let reader = responseReader
            var value = GetForecastOutput()
            value.chanceOfRain = try reader["chanceOfRain"].readIfPresent()
            value.precipitation = try reader["precipitation"].readIfPresent(with: WeatherClientTypes.Precipitation.read(from:))
            return value
        }
    }
}
