// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyHTTPAPI
import SmithyJSON
import SmithyReadWrite

extension GetForecastOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HttpResponse) async throws -> GetForecastOutput {
        let data = try await httpResponse.data()
        let responseReader = try SmithyJSON.Reader.from(data: data)
        let reader = responseReader
        var value = GetForecastOutput()
        value.chanceOfRain = try reader["chanceOfRain"].readIfPresent()
        value.precipitation = try reader["precipitation"].readIfPresent(with: WeatherClientTypes.Precipitation.read(from:))
        return value
    }
}
