// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension GetForecastOutput: ClientRuntime.HttpResponseBinding {
    public init(httpResponse: ClientRuntime.HttpResponse, decoder: ClientRuntime.ResponseDecoder? = nil) async throws {
        if let data = try await httpResponse.body.readData(),
            let responseDecoder = decoder {
            let output: GetForecastOutputBody = try responseDecoder.decode(responseBody: data)
            self.chanceOfRain = output.chanceOfRain
            self.precipitation = output.precipitation
        } else {
            self.chanceOfRain = nil
            self.precipitation = nil
        }
    }
}
