// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyReadWrite

public struct GetForecastOutput {
    public var chanceOfRain: Swift.Float?
    public var precipitation: WeatherClientTypes.Precipitation?

    public init(
        chanceOfRain: Swift.Float? = nil,
        precipitation: WeatherClientTypes.Precipitation? = nil
    )
    {
        self.chanceOfRain = chanceOfRain
        self.precipitation = precipitation
    }
}
