// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct GetForecastInputBody {
}

extension GetForecastInputBody: Swift.Decodable {

    public init(from decoder: Swift.Decoder) throws {
    }
}
