// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct GetForecastInput {
    /// This member is required.
    public var cityId: Swift.String?

    public init(
        cityId: Swift.String? = nil
    )
    {
        self.cityId = cityId
    }
}
