// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyReadWrite

public struct InvokeInput: Swift.Equatable {
    public var payload: ClientRuntime.Data?

    public init(
        payload: ClientRuntime.Data? = nil
    )
    {
        self.payload = payload
    }
}
