// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Foundation
import SmithyReadWrite

public struct InvokeInput {
    public var payload: Foundation.Data?

    public init(
        payload: Foundation.Data? = nil
    )
    {
        self.payload = payload
    }
}
