// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension InvokeOutput: ClientRuntime.HttpResponseBinding {
    public init(httpResponse: ClientRuntime.HttpResponse, decoder: ClientRuntime.ResponseDecoder? = nil) async throws {
        switch httpResponse.body {
        case .data(let data):
            self.payload = data
        case .stream(let stream):
            self.payload = try stream.readToEnd()
        case .noStream:
            self.payload = nil
        }
    }
}
