// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension InvokeInput {

    static func urlPathProvider(_ value: InvokeInput) -> Swift.String? {
        return "/invoke"
    }
}
