// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyJSON
import SmithyReadWrite

extension ListCitiesOutput {

    static var httpBinding: SmithyReadWrite.WireResponseOutputBinding<ClientRuntime.HttpResponse, ListCitiesOutput, SmithyJSON.Reader> {
        { httpResponse, responseDocumentClosure in
            let responseReader = try await responseDocumentClosure(httpResponse)
            let reader = responseReader
            var value = ListCitiesOutput()
            value.items = try reader["items"].readListIfPresent(memberReadingClosure: WeatherClientTypes.CitySummary.read(from:), memberNodeInfo: "member", isFlattened: false)
            value.nextToken = try reader["nextToken"].readIfPresent()
            return value
        }
    }
}
