// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct ListCitiesInput: Swift.Equatable {
    public var nextToken: Swift.String?
    public var pageSize: Swift.Int?

    public init(
        nextToken: Swift.String? = nil,
        pageSize: Swift.Int? = nil
    )
    {
        self.nextToken = nextToken
        self.pageSize = pageSize
    }
}
