// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension ListCitiesInput {

    static func urlPathProvider(_ value: ListCitiesInput) -> Swift.String? {
        return "/cities"
    }
}
