// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct ListCitiesOutput {
    /// This member is required.
    public var items: [WeatherClientTypes.CitySummary]?
    public var nextToken: Swift.String?

    public init(
        items: [WeatherClientTypes.CitySummary]? = nil,
        nextToken: Swift.String? = nil
    )
    {
        self.items = items
        self.nextToken = nextToken
    }
}
