// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyHTTPAPI

extension ListCitiesInput {

    static func queryItemProvider(_ value: ListCitiesInput) throws -> [SmithyHTTPAPI.SDKURLQueryItem] {
        var items = [SmithyHTTPAPI.SDKURLQueryItem]()
        if let nextToken = value.nextToken {
            let nextTokenQueryItem = SmithyHTTPAPI.SDKURLQueryItem(name: "nextToken".urlPercentEncoding(), value: Swift.String(nextToken).urlPercentEncoding())
            items.append(nextTokenQueryItem)
        }
        if let pageSize = value.pageSize {
            let pageSizeQueryItem = SmithyHTTPAPI.SDKURLQueryItem(name: "pageSize".urlPercentEncoding(), value: Swift.String(pageSize).urlPercentEncoding())
            items.append(pageSizeQueryItem)
        }
        return items
    }
}
