// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct ListCitiesInputBody: Swift.Equatable {
}

extension ListCitiesInputBody: Swift.Decodable {

    public init(from decoder: Swift.Decoder) throws {
    }
}
