// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension WeatherClientTypes {
    public struct Message: Swift.Equatable {
        public var author: Swift.String?
        public var message: Swift.String?

        public init(
            author: Swift.String? = nil,
            message: Swift.String? = nil
        )
        {
            self.author = author
            self.message = message
        }
    }

}
