// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct NoSuchResourceBody: Swift.Equatable {
    let resourceType: Swift.String?
    let message: Swift.String?
}

extension NoSuchResourceBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case message
        case resourceType
    }

    public init(from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let resourceTypeDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .resourceType)
        resourceType = resourceTypeDecoded
        let messageDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .message)
        message = messageDecoded
    }
}
