// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyJSON
import SmithyReadWrite
import SmithyTestUtil

extension NoSuchResource {

    static func makeError(baseError: SmithyTestUtil.JSONError) throws -> NoSuchResource {
        let reader = baseError.errorBodyReader
        var value = NoSuchResource()
        value.properties.message = try reader["message"].readIfPresent()
        value.properties.resourceType = try reader["resourceType"].readIfPresent()
        value.httpResponse = baseError.httpResponse
        value.requestID = baseError.requestID
        value.message = baseError.message
        return value
    }
}
