// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension OnlyFakeAuthInput {

    static func urlPathProvider(_ value: OnlyFakeAuthInput) -> Swift.String? {
        return "/OnlyFakeAuth"
    }
}
