// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct OnlyFakeAuthOptionalInputBody: Swift.Equatable {
}

extension OnlyFakeAuthOptionalInputBody: Swift.Decodable {

    public init(from decoder: Swift.Decoder) throws {
    }
}
