// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyHTTPAPI
import SmithyJSON
import SmithyReadWrite

extension OnlyHttpApiKeyAuthOptionalOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HttpResponse) async throws -> OnlyHttpApiKeyAuthOptionalOutput {
        return OnlyHttpApiKeyAuthOptionalOutput()
    }
}
