// Code generated by smithy-swift-codegen. DO NOT EDIT!

import class SmithyHTTPAPI.HttpResponse

extension OnlyHttpApiKeyAuthOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HttpResponse) async throws -> OnlyHttpApiKeyAuthOutput {
        return OnlyHttpApiKeyAuthOutput()
    }
}
