// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension OnlyHttpApiKeyAuthInput {

    static func urlPathProvider(_ value: OnlyHttpApiKeyAuthInput) -> Swift.String? {
        return "/OnlyHttpApiKeyAuth"
    }
}
