// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyJSON
import SmithyReadWrite

extension OnlyFakeAuthOptionalOutput {

    static var httpBinding: SmithyReadWrite.WireResponseOutputBinding<ClientRuntime.HttpResponse, OnlyFakeAuthOptionalOutput, SmithyJSON.Reader> {
        { httpResponse, responseDocumentClosure in
            return OnlyFakeAuthOptionalOutput()
        }
    }
}
