// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension OnlyHttpApiKeyAndBearerAuthInput {

    static func urlPathProvider(_ value: OnlyHttpApiKeyAndBearerAuthInput) -> Swift.String? {
        return "/OnlyHttpApiKeyAndBearerAuth"
    }
}
