// Code generated by smithy-swift-codegen. DO NOT EDIT!

import class SmithyHTTPAPI.HttpResponse

extension OnlyFakeAuthOptionalOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HttpResponse) async throws -> OnlyFakeAuthOptionalOutput {
        return OnlyFakeAuthOptionalOutput()
    }
}
