// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension OnlyHttpApiKeyAuthInput {

    static func urlPathProvider(_ value: OnlyHttpApiKeyAuthInput) -> Swift.String? {
        return "/OnlyHttpApiKeyAuth"
    }
}
