// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyJSON
import SmithyReadWrite

extension OnlyHttpApiKeyAuthOptionalOutput {

    static var httpBinding: SmithyReadWrite.WireResponseOutputBinding<ClientRuntime.HttpResponse, OnlyHttpApiKeyAuthOptionalOutput, SmithyJSON.Reader> {
        { httpResponse, responseDocumentClosure in
            return OnlyHttpApiKeyAuthOptionalOutput()
        }
    }
}
