// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension OnlySigv4AuthInput {

    static func urlPathProvider(_ value: OnlySigv4AuthInput) -> Swift.String? {
        return "/OnlySigv4Auth"
    }
}
