// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyJSON
import SmithyReadWrite

extension OnlySigv4AuthOutput {

    static func httpOutput(from httpResponse: ClientRuntime.HttpResponse) async throws -> OnlySigv4AuthOutput {
        return OnlySigv4AuthOutput()
    }
}
