// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyJSON
import SmithyReadWrite

extension OnlySigv4AuthOptionalOutput {

    static var httpBinding: SmithyReadWrite.WireResponseOutputBinding<ClientRuntime.HttpResponse, OnlySigv4AuthOptionalOutput, SmithyJSON.Reader> {
        { httpResponse, responseDocumentClosure in
            return OnlySigv4AuthOptionalOutput()
        }
    }
}
