// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct OnlySigv4AuthOptionalInputBody {
}

extension OnlySigv4AuthOptionalInputBody: Swift.Decodable {

    public init(from decoder: Swift.Decoder) throws {
    }
}
