// Code generated by smithy-swift-codegen. DO NOT EDIT!

import class SmithyHTTPAPI.HttpResponse

extension OnlyHttpApiKeyAndBearerAuthOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HttpResponse) async throws -> OnlyHttpApiKeyAndBearerAuthOutput {
        return OnlyHttpApiKeyAndBearerAuthOutput()
    }
}
