// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyJSON
import SmithyReadWrite

extension OnlyHttpApiKeyAndBearerAuthOutput {

    static var httpBinding: SmithyReadWrite.WireResponseOutputBinding<ClientRuntime.HttpResponse, OnlyHttpApiKeyAndBearerAuthOutput, SmithyJSON.Reader> {
        { httpResponse, responseDocumentClosure in
            return OnlyHttpApiKeyAndBearerAuthOutput()
        }
    }
}
