// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension OnlyHttpApiKeyAndBearerAuthReversedInput {

    static func urlPathProvider(_ value: OnlyHttpApiKeyAndBearerAuthReversedInput) -> Swift.String? {
        return "/OnlyHttpApiKeyAndBearerAuthReversed"
    }
}
