// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct OnlyHttpApiKeyAuthOptionalInputBody {
}

extension OnlyHttpApiKeyAuthOptionalInputBody: Swift.Decodable {

    public init(from decoder: Swift.Decoder) throws {
    }
}
