// Code generated by smithy-swift-codegen. DO NOT EDIT!

import class SmithyHTTPAPI.HttpResponse

extension OnlyHttpBearerAuthOptionalOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HttpResponse) async throws -> OnlyHttpBearerAuthOptionalOutput {
        return OnlyHttpBearerAuthOptionalOutput()
    }
}
