// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyJSON
import SmithyReadWrite

extension OnlySigv4AuthOptionalOutput {

    static func httpOutput(from httpResponse: ClientRuntime.HttpResponse) async throws -> OnlySigv4AuthOptionalOutput {
        return OnlySigv4AuthOptionalOutput()
    }
}
