// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension OnlyHttpBearerAuthInput {

    static func urlPathProvider(_ value: OnlyHttpBearerAuthInput) -> Swift.String? {
        return "/OnlyHttpBearerAuth"
    }
}
