// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension OnlyHttpBearerAuthOptionalInput {

    static func urlPathProvider(_ value: OnlyHttpBearerAuthOptionalInput) -> Swift.String? {
        return "/OnlyHttpBearerAuthOptional"
    }
}
