// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct OnlyHttpApiKeyAuthInputBody: Swift.Equatable {
}

extension OnlyHttpApiKeyAuthInputBody: Swift.Decodable {

    public init(from decoder: Swift.Decoder) throws {
    }
}
