// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct OnlyFakeAuthInputBody: Swift.Equatable {
}

extension OnlyFakeAuthInputBody: Swift.Decodable {

    public init(from decoder: Swift.Decoder) throws {
    }
}
