// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct OnlyHttpBearerAuthOptionalInputBody: Swift.Equatable {
}

extension OnlyHttpBearerAuthOptionalInputBody: Swift.Decodable {

    public init(from decoder: Swift.Decoder) throws {
    }
}
