// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct OnlyHttpBearerAuthInputBody {
}

extension OnlyHttpBearerAuthInputBody: Swift.Decodable {

    public init(from decoder: Swift.Decoder) throws {
    }
}
