// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension OnlySigv4AuthOptionalInput {

    static func urlPathProvider(_ value: OnlySigv4AuthOptionalInput) -> Swift.String? {
        return "/OnlySigv4AuthOptional"
    }
}
