// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyJSON
import SmithyReadWrite

extension OnlyFakeAuthOutput {

    static var httpBinding: SmithyReadWrite.WireResponseOutputBinding<ClientRuntime.HttpResponse, OnlyFakeAuthOutput, SmithyJSON.Reader> {
        { httpResponse, responseDocumentClosure in
            return OnlyFakeAuthOutput()
        }
    }
}
