// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyHTTPAPI
import SmithyJSON
import SmithyReadWrite
import class SmithyHTTPAPI.HttpResponse

extension OnlyHttpBearerAuthOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HttpResponse) async throws -> OnlyHttpBearerAuthOutput {
        return OnlyHttpBearerAuthOutput()
    }
}
