// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension OnlyHttpApiKeyAuthOptionalInput {

    static func urlPathProvider(_ value: OnlyHttpApiKeyAuthOptionalInput) -> Swift.String? {
        return "/OnlyHttpApiKeyAuthOptional"
    }
}
