// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension OnlyFakeAuthOptionalInput {

    static func urlPathProvider(_ value: OnlyFakeAuthOptionalInput) -> Swift.String? {
        return "/OnlyFakeAuthOptional"
    }
}
