// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyJSON
import SmithyReadWrite

extension OnlyHttpBearerAuthOptionalOutput {

    static var httpBinding: SmithyReadWrite.WireResponseOutputBinding<ClientRuntime.HttpResponse, OnlyHttpBearerAuthOptionalOutput, SmithyJSON.Reader> {
        { httpResponse, responseDocumentClosure in
            return OnlyHttpBearerAuthOptionalOutput()
        }
    }
}
