// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct OnlyHttpApiKeyAndBearerAuthInputBody: Swift.Equatable {
}

extension OnlyHttpApiKeyAndBearerAuthInputBody: Swift.Decodable {

    public init(from decoder: Swift.Decoder) throws {
    }
}
