// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct OnlyHttpApiKeyAndBearerAuthReversedInputBody {
}

extension OnlyHttpApiKeyAndBearerAuthReversedInputBody: Swift.Decodable {

    public init(from decoder: Swift.Decoder) throws {
    }
}
