// Code generated by smithy-swift-codegen. DO NOT EDIT!

import class SmithyHTTPAPI.HttpResponse

extension OnlySigv4AuthOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HttpResponse) async throws -> OnlySigv4AuthOutput {
        return OnlySigv4AuthOutput()
    }
}
