// Code generated by smithy-swift-codegen. DO NOT EDIT!

import class SmithyHTTPAPI.HttpResponse

extension OnlyHttpBearerAuthOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HttpResponse) async throws -> OnlyHttpBearerAuthOutput {
        return OnlyHttpBearerAuthOutput()
    }
}
