// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

enum OnlyHttpApiKeyAndBearerAuthOutputError: ClientRuntime.HttpResponseErrorBinding {
    static func makeError(httpResponse: ClientRuntime.HttpResponse, decoder: ClientRuntime.ResponseDecoder? = nil) async throws -> Swift.Error {
        let restJSONError = try await ClientRuntime.RestJSONError(httpResponse: httpResponse)
        switch restJSONError.errorType {
            default: return try await ClientRuntime.UnknownHTTPServiceError.makeError(httpResponse: httpResponse, message: restJSONError.errorMessage, typeName: restJSONError.errorType)
        }
    }
}
