// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension OnlyHttpApiKeyAndBearerAuthReversedInput {

    static func urlPathProvider(_ value: OnlyHttpApiKeyAndBearerAuthReversedInput) -> Swift.String? {
        return "/OnlyHttpApiKeyAndBearerAuthReversed"
    }
}
