// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyJSON
import SmithyReadWrite

extension OnlyHttpBearerAuthOutput {

    static var httpBinding: SmithyReadWrite.WireResponseOutputBinding<ClientRuntime.HttpResponse, OnlyHttpBearerAuthOutput, SmithyJSON.Reader> {
        { httpResponse, responseDocumentClosure in
            return OnlyHttpBearerAuthOutput()
        }
    }
}
