// Code generated by smithy-swift-codegen. DO NOT EDIT!

import class SmithyHTTPAPI.HttpResponse

extension OnlyHttpApiKeyAndBearerAuthReversedOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HttpResponse) async throws -> OnlyHttpApiKeyAndBearerAuthReversedOutput {
        return OnlyHttpApiKeyAndBearerAuthReversedOutput()
    }
}
