// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyJSON
import SmithyReadWrite

extension OnlyHttpApiKeyAndBearerAuthReversedOutput {

    static func httpOutput(from httpResponse: ClientRuntime.HttpResponse) async throws -> OnlyHttpApiKeyAndBearerAuthReversedOutput {
        return OnlyHttpApiKeyAndBearerAuthReversedOutput()
    }
}
