// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyJSON
import SmithyReadWrite

extension OnlyHttpApiKeyAuthOutput {

    static var httpBinding: SmithyReadWrite.WireResponseOutputBinding<ClientRuntime.HttpResponse, OnlyHttpApiKeyAuthOutput, SmithyJSON.Reader> {
        { httpResponse, responseDocumentClosure in
            return OnlyHttpApiKeyAuthOutput()
        }
    }
}
