// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct OnlySigv4AuthInputBody {
}

extension OnlySigv4AuthInputBody: Swift.Decodable {

    public init(from decoder: Swift.Decoder) throws {
    }
}
