// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyJSON
import SmithyReadWrite

extension OnlyFakeAuthOutput {

    static func httpOutput(from httpResponse: ClientRuntime.HttpResponse) async throws -> OnlyFakeAuthOutput {
        return OnlyFakeAuthOutput()
    }
}
