// Code generated by smithy-swift-codegen. DO NOT EDIT!

import SmithyReadWrite

extension WeatherClientTypes {
    public struct OtherStructure: Swift.Equatable {

        public init() { }
    }

}
