// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension WeatherClientTypes.OtherStructure: Swift.Codable {

    public func encode(to encoder: Swift.Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode([String:String]())
    }

    public init(from decoder: Swift.Decoder) throws {
    }
}
