// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyJSON
import SmithyReadWrite

extension WeatherClientTypes.OtherStructure {

    static func read(from reader: SmithyJSON.Reader) throws -> WeatherClientTypes.OtherStructure {
        guard reader.hasContent else { throw SmithyReadWrite.ReaderError.requiredValueNotPresent }
        return WeatherClientTypes.OtherStructure()
    }
}
