// Code generated by smithy-swift-codegen. DO NOT EDIT!

import Foundation

extension WeatherClientTypes {
    public enum Precipitation {
        case rain(Swift.Bool)
        case sleet(Swift.Bool)
        case hail([Swift.String:Swift.String])
        case snow(WeatherClientTypes.SimpleYesNo)
        case mixed(WeatherClientTypes.TypedYesNo)
        case other(WeatherClientTypes.OtherStructure)
        case blob(Foundation.Data)
        case foo(WeatherClientTypes.Foo)
        case baz(WeatherClientTypes.Baz)
        case sdkUnknown(Swift.String)
    }

}
