// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct SameAsServiceInputBody {
}

extension SameAsServiceInputBody: Swift.Decodable {

    public init(from decoder: Swift.Decoder) throws {
    }
}
