// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension SameAsServiceInput {

    static func urlPathProvider(_ value: SameAsServiceInput) -> Swift.String? {
        return "/SameAsService"
    }
}
