// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension SameAsServiceInput {

    static func urlPathProvider(_ value: SameAsServiceInput) -> Swift.String? {
        return "/SameAsService"
    }
}
