// Code generated by smithy-swift-codegen. DO NOT EDIT!

import SmithyTestUtil
import class SmithyHTTPAPI.HttpResponse
import class SmithyJSON.Reader
import struct ClientRuntime.UnknownHTTPServiceError

enum SameAsServiceOutputError {

    static func httpError(from httpResponse: SmithyHTTPAPI.HttpResponse) async throws -> Swift.Error {
        let data = try await httpResponse.data()
        let responseReader = try SmithyJSON.Reader.from(data: data)
        let baseError = try SmithyTestUtil.TestBaseError(httpResponse: httpResponse, responseReader: responseReader, noErrorWrapping: false)
        if let error = baseError.customError() { return error }
        switch baseError.code {
            default: return try ClientRuntime.UnknownHTTPServiceError.makeError(baseError: baseError)
        }
    }
}
