// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import SmithyJSON
import SmithyReadWrite

extension SameAsServiceOutput {

    static var httpBinding: SmithyReadWrite.WireResponseOutputBinding<ClientRuntime.HttpResponse, SameAsServiceOutput, SmithyJSON.Reader> {
        { httpResponse, responseDocumentClosure in
            return SameAsServiceOutput()
        }
    }
}
