/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0.
 */

plugins {
    java
    id("software.amazon.smithy.gradle.smithy-base")
}

val smithyVersion: String by project

dependencies {
    implementation("software.amazon.smithy:smithy-aws-traits:$smithyVersion")
    implementation(project(":smithy-swift-codegen"))
}

data class TestSDK(val name: String, val forceSchemaBased: Boolean = false)

val testSDKs = listOf(
    TestSDK("AWSJSON"),
    TestSDK("JSONName"),
    TestSDK("HTTPLabel", true),
    TestSDK("HTTPQuery", true),
    TestSDK("MaxRecursion"),
    TestSDK("NullTolerance"),
    TestSDK("StringSerializer"),
    TestSDK("Waiters"),
)

fun generateProjection(sdk: TestSDK): String {
    val forceSchemaBasedLine = if (sdk.forceSchemaBased) ",\n          \"forceSchemaBased\": true" else ""
    return """
    "${sdk.name}": {
      "transforms": [
        {
          "name": "includeServices",
          "args": {
            "services": [
              "smithy.swift.tests.${sdk.name}#${sdk.name}"
            ]
          }
        },
        {
          "name": "removeUnusedShapes"
        },
        {
          "name": "flattenAndRemoveMixins"
        }
      ],
      "plugins": {
        "swift-codegen": {
          "service": "smithy.swift.tests.${sdk.name}#${sdk.name}",
          "module": "${sdk.name}TestSDK",
          "moduleVersion": "0.0.1",
          "gitRepo": "https://github.com/smithy-lang/smithy-swift.git",
          "author": "Amazon Web Services",
          "homepage": "https://docs.aws.amazon.com/sdk-for-swift/",
          "swiftVersion": "5.9.0",
          "mergeModels": true,
          "copyrightNotice": "//\n// Copyright Amazon.com Inc. or its affiliates.\n// All Rights Reserved.\n//\n// SPDX-License-Identifier: Apache-2.0\n//\n\n// Code generated by smithy-swift-codegen. DO NOT EDIT!\n\n",
          "localDevelopment": true$forceSchemaBasedLine
        }
      }
    }""".trimIndent()
}

fun generateSmithyBuild(): String {
    val projections = testSDKs.joinToString(",\n") { generateProjection(it).prependIndent("    ") }
    return """
{
  "version": "1.0",
  "projections": {
$projections
  }
}
"""
}

tasks.register("generateSmithyBuild") {
    description = "generate smithy-build.json"
    doFirst {
        projectDir.resolve("smithy-build.json").writeText(generateSmithyBuild())
    }
}

tasks.named("smithyBuild") {
    dependsOn("generateSmithyBuild")
}

tasks["jar"].enabled = false

tasks["clean"].doFirst {
    delete("smithy-build.json")
}
