/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0.
 */

import software.amazon.smithy.gradle.tasks.SmithyBuild
import software.amazon.smithy.model.shapes.ShapeId
import software.amazon.smithy.model.node.Node

plugins {
    id("software.amazon.smithy").version("0.5.3")
}

val smithyVersion: String by project

buildscript {
    val smithyVersion: String by project
    dependencies {
        classpath("software.amazon.smithy:smithy-cli:$smithyVersion")
    }
}

dependencies {
    implementation("software.amazon.smithy:smithy-aws-traits:$smithyVersion")
    implementation(project(":smithy-swift-codegen"))
}

fun generateSmithyBuild(): String {
    return """
{
  "version": "1.0",
  "projections": {
    "rpcv2cbor": {
      "transforms": [
        {
          "name": "includeServices",
          "args": {
            "services": [
              "smithy.swift.tests#RPCv2CBORService"
            ]
          }
        },
        {
          "name": "removeUnusedShapes"
        },
        {
          "name": "flattenAndRemoveMixins"
        }
      ],
      "plugins": {
        "swift-codegen": {
          "service": "smithy.swift.tests#RPCv2CBORService",
          "module": "RPCv2CBORTestSDK",
          "moduleVersion": "0.0.1",
          "gitRepo": "https://github.com/smithy-lang/smithy-swift.git",
          "author": "Amazon Web Services",
          "homepage": "https://docs.aws.amazon.com/sdk-for-swift/",
          "swiftVersion": "5.9.0",
          "mergeModels": true,
          "copyrightNotice": "//\n// Copyright Amazon.com Inc. or its affiliates.\n// All Rights Reserved.\n//\n// SPDX-License-Identifier: Apache-2.0\n//\n\n// Code generated by smithy-swift-codegen. DO NOT EDIT!\n\n"
        }
      }
    },
    "awsjson": {
      "transforms": [
        {
          "name": "includeServices",
          "args": {
            "services": [
              "smithy.swift.tests#AWSJSONService"
            ]
          }
        },
        {
          "name": "removeUnusedShapes"
        },
        {
          "name": "flattenAndRemoveMixins"
        }
      ],
      "plugins": {
        "swift-codegen": {
          "service": "smithy.swift.tests#AWSJSONService",
          "module": "AWSJSONTestSDK",
          "moduleVersion": "0.0.1",
          "gitRepo": "https://github.com/smithy-lang/smithy-swift.git",
          "author": "Amazon Web Services",
          "homepage": "https://docs.aws.amazon.com/sdk-for-swift/",
          "swiftVersion": "5.9.0",
          "mergeModels": true,
          "copyrightNotice": "//\n// Copyright Amazon.com Inc. or its affiliates.\n// All Rights Reserved.\n//\n// SPDX-License-Identifier: Apache-2.0\n//\n\n// Code generated by smithy-swift-codegen. DO NOT EDIT!\n\n"
        }
      }
    }
  }
}
"""
}

tasks.create<SmithyBuild>("buildSdk") {
    addRuntimeClasspath = true
}

task("generateSmithyBuild") {
    description = "generate smithy-build.json"
    doFirst {
        projectDir.resolve("smithy-build.json").writeText(generateSmithyBuild())
    }
}
tasks["jar"].enabled = false
tasks["smithyBuildJar"].dependsOn("generateSmithyBuild")

tasks["clean"].doFirst {
    delete("smithy-build.json")
}

