// Code generated by smithy-swift-codegen. DO NOT EDIT!

import SmithyTestUtil
import WeatherSDK

extension WeatherClientTypes.CityCoordinates: Swift.Equatable {

    public static func ==(lhs: WeatherClientTypes.CityCoordinates, rhs: WeatherClientTypes.CityCoordinates) -> Bool {
        if (!floatingPointValuesMatch(lhs: lhs.latitude, rhs: rhs.latitude)) { return false }
        if (!floatingPointValuesMatch(lhs: lhs.longitude, rhs: rhs.longitude)) { return false }
        return true
    }
}
