// Code generated by smithy-swift-codegen. DO NOT EDIT!

import SmithyTestUtil
import WeatherSDK

extension WeatherClientTypes.CitySummary: Swift.Equatable {

    public static func ==(lhs: WeatherClientTypes.CitySummary, rhs: WeatherClientTypes.CitySummary) -> Bool {
        if lhs.cityId != rhs.cityId { return false }
        if lhs.name != rhs.name { return false }
        if lhs.number != rhs.number { return false }
        if lhs.`case` != rhs.`case` { return false }
        return true
    }
}
