// Code generated by smithy-swift-codegen. DO NOT EDIT!

import SmithyTestUtil
import WeatherSDK

extension GetCityOutput: Swift.Equatable {

    public static func ==(lhs: GetCityOutput, rhs: GetCityOutput) -> Bool {
        if lhs.name != rhs.name { return false }
        if lhs.coordinates != rhs.coordinates { return false }
        if lhs.city != rhs.city { return false }
        return true
    }
}
