// Code generated by smithy-swift-codegen. DO NOT EDIT!

import SmithyTestUtil
import WeatherSDK

extension GetCityAnnouncementsOutput: Swift.Equatable {

    public static func ==(lhs: GetCityAnnouncementsOutput, rhs: GetCityAnnouncementsOutput) -> Bool {
        if lhs.lastUpdated != rhs.lastUpdated { return false }
        return true
    }
}
