// Code generated by smithy-swift-codegen. DO NOT EDIT!

import SmithyTestUtil
import WeatherSDK

extension GetCityImageInput: Swift.Equatable {

    public static func ==(lhs: GetCityImageInput, rhs: GetCityImageInput) -> Bool {
        if lhs.cityId != rhs.cityId { return false }
        return true
    }
}
