// Code generated by smithy-swift-codegen. DO NOT EDIT!

import SmithyTestUtil
import WeatherSDK

extension GetCityAnnouncementsInput: Swift.Equatable {

    public static func ==(lhs: GetCityAnnouncementsInput, rhs: GetCityAnnouncementsInput) -> Bool {
        if lhs.cityId != rhs.cityId { return false }
        return true
    }
}
