// Code generated by smithy-swift-codegen. DO NOT EDIT!

import SmithyTestUtil
import WeatherSDK

extension GetCityInput: Swift.Equatable {

    public static func ==(lhs: GetCityInput, rhs: GetCityInput) -> Bool {
        if lhs.cityId != rhs.cityId { return false }
        return true
    }
}
