// Code generated by smithy-swift-codegen. DO NOT EDIT!

import SmithyTestUtil
import WeatherSDK

extension GetCityImageOutput: Swift.Equatable {

    public static func ==(lhs: GetCityImageOutput, rhs: GetCityImageOutput) -> Bool {
        if lhs.image != rhs.image { return false }
        return true
    }
}
