// Code generated by smithy-swift-codegen. DO NOT EDIT!

import SmithyTestUtil
import WeatherSDK

extension ListCitiesInput: Swift.Equatable {

    public static func ==(lhs: ListCitiesInput, rhs: ListCitiesInput) -> Bool {
        return true
    }
}
