// Code generated by smithy-swift-codegen. DO NOT EDIT!

import SmithyTestUtil
import WeatherSDK

extension NoSuchResource: Swift.Equatable {

    public static func ==(lhs: NoSuchResource, rhs: NoSuchResource) -> Bool {
        if lhs.properties.resourceType != rhs.properties.resourceType { return false }
        if lhs.properties.message != rhs.properties.message { return false }
        return true
    }
}
