// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime
import Smithy
import SmithyTestUtil
@testable import WeatherSDK
import XCTest


class ListCitiesRequestTest: HttpRequestTestBase {
    /// Does something
    func testWriteListCitiesAssertions() async throws {
        let urlPrefix = urlPrefixFromHost(host: "")
        let hostOnly = hostOnlyFromHost(host: "")
        let expected = buildExpectedHttpRequest(
            method: .get,
            path: "/cities",
            queryParams: [
                "pageSize=50"
            ],
            forbiddenQueryParams: [
                "nextToken"
            ],
            body: nil,
            host: "example.com",
            resolvedHost: "example.com"
        )

        let config = try await WeatherClient.WeatherClientConfiguration()
        config.region = "us-west-2"
        config.httpClientEngine = ProtocolTestClient()
        config.idempotencyTokenGenerator = ProtocolTestIdempotencyTokenGenerator()
        let client = WeatherClient(config: config)

        let input = ListCitiesInput(
            pageSize: 50
        )
        do {
            _ = try await client.listCities(input: input)
        } catch TestCheckError.actual(let actual) {
            try await self.assertEqual(expected, actual)
        }
    }
}
