// Code generated by smithy-swift-codegen. DO NOT EDIT!

import class ClientRuntime.EndpointsRequestContext
import protocol ClientRuntime.EndpointsRequestContextProviding

public struct EndpointParams {
    /// docs
    public let region: Swift.String

    public init(
        region: Swift.String
    )
    {
        self.region = region
    }
}

extension EndpointParams: ClientRuntime.EndpointsRequestContextProviding {

    public var context: ClientRuntime.EndpointsRequestContext {
        get throws {
            let context = try ClientRuntime.EndpointsRequestContext()
            try context.add(name: "Region", value: self.region)
            return context
        }
    }
}
