#if !canImport(ObjectiveC)
import XCTest

extension HttpRequestTestBaseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HttpRequestTestBaseTests = [
        ("testJSONEqual", testJSONEqual),
        ("testSayHello", testSayHello),
    ]
}

extension HttpResponseTestBaseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HttpResponseTestBaseTests = [
        ("testBuildHttpResponse", testBuildHttpResponse),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HttpRequestTestBaseTests.__allTests__HttpRequestTestBaseTests),
        testCase(HttpResponseTestBaseTests.__allTests__HttpResponseTestBaseTests),
    ]
}
#endif
