description = "XML serialization and deserialization for Smithy services generated by smithy-kotlin"
extra["displayName"] = "Smithy :: Kotlin :: Serde :: XML"
extra["moduleName"] = "software.aws.clientrt.serde.xml"

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                api(project(":client-runtime:serde"))
            }
        }
        jvmMain {
            dependencies {
                // implementation("com.google.code.gson:gson:$gsonVersion")
            }
        }
    }
}
