name: Swift6 Compatibility

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  AWS_SWIFT_SDK_USE_LOCAL_DEPS: 1

jobs:
  bump-swift-tools-version:
    if: github.repository == 'smithy-lang/smithy-swift' || github.event_name == 'pull_request'
    runs-on: macos-26
    steps:
      - name: Checkout smithy-swift
        uses: actions/checkout@v4
      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_26.4.app
      - name: Setup common tools
        uses: ./.github/actions/setup-common-tools-composite-action
      - name: Generate test SDKs
        run: ./scripts/codegen.sh
      - name: Build on swift-tools-version 6.0
        run: |
          swift package tools-version --set 6.0
          swift build
